theme = 'ananke'
title = 'Vulcanizare Mobila - Non Stop'
baseURL = 'https://vulcanizaremobila.com/'

description = 'Vulcanizare mobilă non-stop în județele Vrancea, Buzău, Adjud și Tecuci. Servicii rapide și accesibile, disponibile 24/7, cu cea mai avansată tehnologie pentru orice tip de mașină. Sună acum pentru asistență!'